let coches = {
  misFavoritos: [
    {
      descripcion: "Coche deportivo",
      modelo: "Ferrari F8 Tributo",
      color: "Rojo",
      asiento: 2,
      llantas: "19 pulgadas",
      cilindrada: 3.9,
      peso: "1.435 kg",
      longitud: "4.61 m",
      plazas: 2,
      informacion: {
        marca: "Ferrari",
        anio: 2019,
      },
    },
    {
      descripcion: "Coche familiar",
      modelo: "Volkswagen Golf",
      color: "Gris",
      asiento: 5,
      llantas: "17 pulgadas",
      cilindrada: 1.5,
      peso: "1.280 kg",
      longitud: "4.28 m",
      plazas: 5,
      informacion: {
        marca: "Volkswagen",
        anio: 1974,
      },
    },
    {
      descripcion: "Coche todoterreno",
      modelo: "Land Rover Defender",
      color: "Verde",
      asiento: 5,
      llantas: "18 pulgadas",
      cilindrada: 2.0,
      peso: "2.114 kg",
      longitud: "4.58 m",
      plazas: 5,
      informacion: {
        marca: "Land Rover",
        anio: 1948,
      },
    },
    {
      descripcion: "Coche deportivo",
      modelo: "Porsche 911",
      color: "Blanco",
      asiento: 2,
      llantas: "20 pulgadas",
      cilindrada: 3.0,
      peso: "1.420 kg",
      longitud: "4.52 m",
      plazas: 2,
      informacion: {
        marca: "Porsche",
        anio: 1963,
      },
    },
    {
      descripcion: "Coche deportivo",
      modelo: "Lamborghini Huracan",
      color: "Amarillo",
      asiento: 2,
      llantas: "20 pulgadas",
      cilindrada: 5.2,
      peso: "1.422 kg",
      longitud: "4.52 m",
      plazas: 2,
      informacion: {
        marca: "Lamborghini",
        anio: 2014,
      },
    },
    {
      descripcion: "Coche urbano",
      modelo: "Renault Twingo",
      color: "Rojo",
      asiento: 4,
      llantas: "15 pulgadas",
      cilindrada: 0.9,
      peso: "930 kg",
      longitud: "3.61 m",
      plazas: 4,
      informacion: {
        marca: "Renault",
        anio: 1993,
      },
    },
    {
        descripcion: "Coche deportivo",
        modelo: "Ferrari 812 Superfast",
        color: "Rojo",
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 6.5,
        peso: "1.650 kg",
        longitud: "4.72 m",
        plazas: 2,
        informacion: {
            marca: "Ferrari",
            anio: 2017,
        },
    },
    {
      descripcion: "Coche todoterreno",
      modelo: "Jeep Wrangler",
      color: "Negro",
      asiento: 4,
      llantas: "17 pulgadas",
      cilindrada: 3.6,
      peso: "1.948 kg",
      longitud: "4.24 m",
      plazas: 4,
      informacion: {
        marca: "Jeep",
        anio: 1986,
      },
    },
    {
        descripcion: "Coche deportivo",
        modelo: "Aston Martin DB11",
        color:"Verde",  
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 5.2,
        peso: "1.950 kg",
        longitud: "4.72 m",
        plazas: 2,  
        informacion: {
            marca: "Aston Martin",
            anio: 2016,
        },
    },
    {
        descripcion: "Coche deportivo", 
        modelo: "Maserati GranTurismo",
        color: "Rojo",
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 4.7,
        peso: "1.850 kg",
        longitud: "4.65 m",
        plazas: 2,
        informacion: {
            marca: "Maserati",
            anio: 2007,
        },
    },
    {
        descripcion: "Coche deportivo",
        modelo: "Audi R8",
        color: "Gris",
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 5.2,
        peso: "1.650 kg",
        longitud: "4.42 m",
        plazas: 2,
        informacion: {
            marca: "Audi",
            anio: 2015,
        },
    }
  ],
};


let coches2 = {
  misFavoritos: [
    {
      descripcion: "Coche no deportivo",
      modelo: "audi F8 Tributo",
      color: "Rojo",
      asiento: 2,
      llantas: "19 pulgadas",
      cilindrada: 3.9,
      peso: "1.435 kg",
      longitud: "4.61 m",
      plazas: 2,
      informacion: {
        marca: "Ferrari",
        anio: 2019,
      },
    },
    {
      descripcion: "Coche familiar",
      modelo: "Volkswagen Golf",
      color: "Gris",
      asiento: 5,
      llantas: "17 pulgadas",
      cilindrada: 1.5,
      peso: "1.280 kg",
      longitud: "4.28 m",
      plazas: 5,
      informacion: {
        marca: "Volkswagen",
        anio: 1974,
      },
    },
    {
      descripcion: "Coche todoterreno",
      modelo: "Land Rover Defender",
      color: "Verde",
      asiento: 5,
      llantas: "18 pulgadas",
      cilindrada: 2.0,
      peso: "2.114 kg",
      longitud: "4.58 m",
      plazas: 5,
      informacion: {
        marca: "Land Rover",
        anio: 1948,
      },
    },
    {
      descripcion: "Coche deportivo",
      modelo: "Porsche 911",
      color: "Blanco",
      asiento: 2,
      llantas: "20 pulgadas",
      cilindrada: 3.0,
      peso: "1.420 kg",
      longitud: "4.52 m",
      plazas: 2,
      informacion: {
        marca: "Porsche",
        anio: 1963,
      },
    },
    {
      descripcion: "Coche deportivo",
      modelo: "Lamborghini Huracan",
      color: "Amarillo",
      asiento: 2,
      llantas: "20 pulgadas",
      cilindrada: 5.2,
      peso: "1.422 kg",
      longitud: "4.52 m",
      plazas: 2,
      informacion: {
        marca: "Lamborghini",
        anio: 2014,
      },
    },
    {
      descripcion: "Coche urbano",
      modelo: "Renault Twingo",
      color: "Rojo",
      asiento: 4,
      llantas: "15 pulgadas",
      cilindrada: 0.9,
      peso: "930 kg",
      longitud: "3.61 m",
      plazas: 4,
      informacion: {
        marca: "Renault",
        anio: 1993,
      },
    },
    {
        descripcion: "Coche deportivo",
        modelo: "Ferrari 812 Superfast",
        color: "Rojo",
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 6.5,
        peso: "1.650 kg",
        longitud: "4.72 m",
        plazas: 2,
        informacion: {
            marca: "Ferrari",
            anio: 2017,
        },
    },
    {
      descripcion: "Coche todoterreno",
      modelo: "Jeep Wrangler",
      color: "Negro",
      asiento: 4,
      llantas: "17 pulgadas",
      cilindrada: 3.6,
      peso: "1.948 kg",
      longitud: "4.24 m",
      plazas: 4,
      informacion: {
        marca: "Jeep",
        anio: 1986,
      },
    },
    {
        descripcion: "Coche deportivo",
        modelo: "Aston Martin DB11",
        color:"Verde",  
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 5.2,
        peso: "1.950 kg",
        longitud: "4.72 m",
        plazas: 2,  
        informacion: {
            marca: "Aston Martin",
            anio: 2016,
        },
    },
    {
        descripcion: "Coche deportivo", 
        modelo: "Maserati GranTurismo",
        color: "Rojo",
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 4.7,
        peso: "1.850 kg",
        longitud: "4.65 m",
        plazas: 2,
        informacion: {
            marca: "Maserati",
            anio: 2007,
        },
    },
    {
        descripcion: "Coche deportivo",
        modelo: "Audi R8",
        color: "Gris",
        asiento: 2,
        llantas: "20 pulgadas",
        cilindrada: 5.2,
        peso: "1.650 kg",
        longitud: "4.42 m",
        plazas: 2,
        informacion: {
            marca: "Audi",
            anio: 2015,
        },
    }
  ],
};
